#!/bin/bash
#Script created to invoke jmeter test script with the slave POD IP addresses
#Script should be run like: ./load_test "path to the test script in jmx format"
# /jmeter/apache-jmeter-5.0/bin/jmeter -n -t $1 -Dserver.rmi.ssl.disable=true -JThreadGroup.num_threads=10000 -JThreadGroup.ramp_time=10 -JLoopController.loops=10 -Jhttpclient4.time_to_live=keep-alive -Jhttpclient.reset_state_on_thread_group_iteration=true -l /tmp/test.csv -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`
/jmeter/apache-jmeter-5.0/bin/jmeter -n -t $1 -JusersFile=$2 -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`
